### PR TITLE
Add option to insatiate profiler using xcactivitylog path

### PR DESCRIPTION
**Pull request by aChase55**

### CODE REVIEW

**Comment by pschneider** [comment]
@giginet Hey! Is this something feasible to add? We use a custom build directory (within the repo path `./build/`) and xcprofiler seems to not work without passing a custom path for the activity log:

```
bundle exec xcprofiler --derived-data-path build/Logs/Build/*.xcactivitylog
```

**Comment by giginet** [comment]
Sorry. I missed this PR for over 1 year... 🙇 

I'll check this tomorrow. Sorry for your patience.

**Review by giginet — APPROVED** [review]
Sorry to keep you waiting such a long time.

I'll fix CI and release this ASAP.

Thank you!

**Comment by giginet** [comment]
@aChase55 @pschneider Sorry for such a long time 🙏 
I just released 0.5.0

**Comment by aChase55** [comment]
Its okay! I forgot I had opened it! Thanks for merging 👍

**Pull request merged**
